from __future__ import annotations

import json
import unittest

from robot_station.config import ROOT, StationConfig
from robot_station.motion import MotionCore
from robot_station.world import World


class ArmOnlyStationTests(unittest.TestCase):
    def test_snapshot_has_no_chassis_or_bunker(self) -> None:
        core = MotionCore(StationConfig(open_browser=False))
        snap = core.snapshot()
        self.assertNotIn("chassis", snap)
        self.assertNotIn("bunker", snap)
        self.assertIn("arm", snap)
        self.assertIn("camera", snap)

    def test_world_has_no_chassis(self) -> None:
        self.assertNotIn("chassis", World().as_dict())
        self.assertNotIn("bunker", World().as_dict())

    def test_chassis_adapters_removed(self) -> None:
        adapters = ROOT / "robot_station" / "adapters"
        self.assertFalse((adapters / "chassis.py").is_file())
        self.assertFalse((adapters / "bunker.py").is_file())

    def test_html_has_no_drive_page(self) -> None:
        html = (ROOT / "robot_station" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        lab = (ROOT / "robot_station" / "web" / "static" / "lab.html").read_text(encoding="utf-8")
        js = (ROOT / "robot_station" / "web" / "static" / "js" / "app.js").read_text(encoding="utf-8")
        self.assertNotIn('id="page-chassis"', html)
        self.assertNotIn("sendStick", js)
        self.assertNotIn('t: "s"', js)
        self.assertNotIn("data-bunker-open", html)
        self.assertNotIn("9101", lab)
        self.assertNotIn("bunkerDriveUrl", js)
        self.assertNotIn("工控机", html)
        self.assertNotIn("工控机", lab)
        self.assertIn("collectBanner", html)
        self.assertIn("btnArmEnable", html)
        self.assertIn('id="connAck"', html)
        self.assertIn('data-hot="disconnect"', html)
        self.assertIn('data-hot="disable"', html)
        self.assertIn("beginCmd", js)
        self.assertIn("paintCmdButtons", js)
        self.assertIn("fireLink", js)
        self.assertIn("firePower", js)
        css = (ROOT / "robot_station" / "web" / "static" / "css" / "app.css").read_text(encoding="utf-8")
        self.assertIn("button:active:not(:disabled)", css)
        self.assertIn("button.busy", css)
        self.assertIn("button.is-on", css)
        self.assertIn("hotkeyBar", html)
        self.assertIn("btnHotkeys", html)
        self.assertIn("快捷键", html)
        self.assertIn("CMD_KEYS", js)
        self.assertIn("fireHotCmd", js)
        self.assertIn("fireEstop", js)
        self.assertIn("flashHot", js)
        self.assertIn("KeyH", js)
        self.assertIn("motorTable", html)
        self.assertIn("t: \"power\"", js)
        self.assertIn('id="panel-twin"', html)
        self.assertIn('id="arm3dHost"', html)
        self.assertIn('data-panel="twin"', html)
        self.assertIn("/static/js/arm3d.js", html)
        self.assertIn("/static/vendor/three.min.js", html)
        self.assertIn("Arm3D.setPose", js)
        self.assertNotIn("没有 3D 孪生", html)
        self.assertNotIn("function fakeEE", js)
        self.assertIn("cartHeld.size", js)
        self.assertIn('typ !== "range"', js)
        self.assertIn('id="spaceBtns"', html)
        self.assertIn('data-space="cart"', html)
        self.assertIn('id="cartList"', html)
        self.assertNotIn('id="cartPad"', html)
        self.assertIn("setSpace", js)
        self.assertIn("bindCartSliders", js)
        self.assertIn("cart_go", js)
        self.assertIn("sendCartPose", js)
        self.assertIn("paintCommandedJoints", js)
        self.assertIn("flushSnap", js)
        self.assertIn("/ws/rtt", js)
        self.assertIn("echo_t0", js)
        self.assertIn("applyEchoRtt", js)
        self.assertIn("sendPing", js)
        self.assertIn("/ws/cmd", js)
        self.assertIn("connectTelem", js)
        self.assertIn("parseTelem", js)
        self.assertIn("0x314E5453", js)
        self.assertIn("teleopHot", js)
        self.assertIn("wantJointStream", js)
        self.assertIn("stopFollowStream", js)
        self.assertIn("jointDirty", js)
        self.assertNotIn("function liveFafu", js)
        self.assertNotIn("liveFafu() && jointsPrimed()", js)
        self.assertNotIn("首次拖动自动勾选", (ROOT / "docs" / "SPEC.md").read_text(encoding="utf-8"))
        self.assertNotIn("真机首次拖动会自动勾选", html)
        self.assertIn('t: "park"', js)
        self.assertIn("setArmSrc", js)
        self.assertIn("btnArmSim", html)
        self.assertIn("jointsPrimed", js)
        self.assertIn("10 * dt", js)
        fafu = (ROOT / "robot_station" / "adapters" / "fafu_arm.py").read_text(encoding="utf-8")
        self.assertIn("LIVE_TELEOP_MAX_DEG_S", fafu)
        self.assertIn("_slew_live_cmd", fafu)
        self.assertIn("_home_waypoints_deg", fafu)
        self.assertIn("HOME_Z_FLOOR_M", fafu)
        self.assertIn("_min_j3_for_table_clear", fafu)
        self.assertIn("_send_zero_vel_hold", fafu)
        self.assertIn("_run_station_gravity", fafu)
        self.assertIn("_recover_dead_gravity", fafu)
        self.assertIn("_vec_to_sdk", fafu)
        self.assertIn("apply_compensation_torque", fafu)
        self.assertIn("STREAM_IDLE_S", fafu)
        self.assertIn("_hold_stream_pose", fafu)
        self.assertIn("_sdk_servoing", fafu)
        self.assertIn("_clear_joint_watchdogs", fafu)
        self.assertIn("SERVO_WATCHDOG_MS", fafu)
        self.assertIn("step_cartesian", fafu)
        self.assertIn("inverse_tracik", fafu)
        self.assertIn("_shoulder_safe_waypoints", fafu)
        self.assertIn("lag_abort_consecutive=0", fafu)
        self.assertIn("Do not call SDK emergency_stop", fafu)
        self.assertIn("_grip_kwargs", fafu)
        self.assertIn("set_pos_vel_tqe", (ROOT / "docs" / "SPEC.md").read_text(encoding="utf-8"))
        self.assertIn("连续示教轨迹", (ROOT / "docs" / "SPEC.md").read_text(encoding="utf-8"))
        self.assertIn('id="panel-traj"', html)
        self.assertIn("btnRecStart", html)
        self.assertIn("btnRecDelete", html)
        self.assertIn('data-traj-teach="drag"', html)
        self.assertIn("btnWpAdd", html)
        self.assertIn('t: "rec_start"', js)
        self.assertIn('t: "rec_delete"', js)
        self.assertIn('t: "replay"', js)
        self.assertIn("delete_recording", (ROOT / "robot_station" / "traj.py").read_text(encoding="utf-8"))
        self.assertIn("_replay_approach_waypoints", fafu)
        self.assertIn("/api/traj", (ROOT / "robot_station" / "web" / "server.py").read_text(encoding="utf-8"))
        self.assertIn("modeCapHint", html)
        self.assertIn("需 pinocchio", html)
        self.assertIn("paintCtrlMode", js)
        self.assertIn("float_ok", js)
        self.assertIn("gripEffort", html)
        self.assertIn("Space: \"grip-toggle\"", js)
        self.assertIn("toggleGripper", js)
        self.assertIn("gripperIsOpen", js)
        self.assertNotIn("KeyO: \"grip-open\"", js)
        self.assertNotIn("ev.code === \"Space\"", js)
        self.assertIn("grip-toggle", html)
        self.assertIn("currentGripEffort", js)
        self.assertIn("effort: currentGripEffort()", js)
        self.assertIn("new Worker", js)
        self.assertIn("connectRttSocket", js)
        self.assertIn("nudgeSockets", js)
        self.assertIn("visibilitychange", js)
        self.assertIn("prev.onclose = null", js)
        self.assertIn("AbortController", js)
        server = (ROOT / "robot_station" / "web" / "server.py").read_text(encoding="utf-8")
        self.assertIn('"/ws/rtt"', server)
        self.assertIn('"/ws/cmd"', server)
        self.assertIn('("/ws", "/ws/cmd", "/ws/video", "/ws/rtt")', server)
        self.assertIn("_teleop_hot", server)
        self.assertIn('kind == "park"', server)
        self.assertIn('kind == "arm_src"', server)
        self.assertIn("err_hud", server)
        motion = (ROOT / "robot_station" / "motion.py").read_text(encoding="utf-8")
        self.assertIn("pack_telem", motion)
        self.assertIn("on_arm_src", motion)
        self.assertIn("broadcast_raw", motion)
        bridge = (ROOT / "robot_station" / "bridge.py").read_text(encoding="utf-8")
        self.assertIn("take_motion_frames", bridge)
        self.assertIn("_stream_latest", bridge)
        self.assertIn("coalesce_stream", bridge)
        self.assertIn("STREAM_RESTART_DEG", fafu)
        self.assertIn("_with_soft_precheck", fafu)
        self.assertIn("_q_rad_from_states", fafu)
        self.assertIn("_joints_enabled", fafu)
        self.assertIn("link_err", (ROOT / "robot_station" / "world.py").read_text(encoding="utf-8"))
        self.assertIn("timeout_s=20.0", (ROOT / "robot_station" / "service.py").read_text(encoding="utf-8"))
        self.assertIn("已重连运动进程", (ROOT / "robot_station" / "bridge.py").read_text(encoding="utf-8"))
        self.assertIn("机械臂未连接", (ROOT / "robot_station" / "motion.py").read_text(encoding="utf-8"))
        self.assertIn("部分轴离线", js)
        self.assertIn("轴在线", js)
        cam = (ROOT / "robot_station" / "adapters" / "camera.py").read_text(encoding="utf-8")
        self.assertIn("set_paused", cam)
        self.assertIn("pick_work_camera", cam)
        self.assertIn("AutoCameraBank", cam)
        self.assertIn("js-cam-overlay", html)
        self.assertIn("shortCamName", js)
        self.assertIn("camLive", js)
        self.assertNotIn("leaseBanner", html)
        self.assertNotIn("wantDriver", js)
        self.assertNotIn("btnLogin", html)
        self.assertNotIn("拿控制权", html)
        self.assertNotIn("拿控制权", js)
        self.assertNotIn("chassis", js)
        self.assertNotIn("bunker", js)
        self.assertIn("127.0.0.1", lab)
        self.assertEqual(StationConfig().camera_count, 1)
        self.assertIn('id="cam0"', html)
        self.assertNotIn('id="cam1"', html)
        self.assertNotIn('id="homeCam1"', html)
        self.assertNotIn("作业相机 A", html)
        self.assertNotIn("作业相机 B", html)
        self.assertNotIn("作业相机 A", js)
        self.assertIn("作业相机", html)
        self.assertIn("cams-home", html)
        self.assertIn("cams-mini", (ROOT / "robot_station" / "web" / "static" / "css" / "app.css").read_text(encoding="utf-8"))

    def test_arm3d_assets_present(self) -> None:
        static = ROOT / "robot_station" / "web" / "static"
        three = static / "vendor" / "three.min.js"
        arm3d = (static / "js" / "arm3d.js").read_text(encoding="utf-8")
        self.assertTrue(three.is_file())
        self.assertGreater(three.stat().st_size, 100_000)
        self.assertIn("fafu_baseV1.urdf", arm3d)
        self.assertIn("fafu_follower.urdf", arm3d)
        self.assertIn("/static/meshes/", arm3d)
        self.assertIn("parseFarm", arm3d)
        self.assertIn("fitCamera", arm3d)
        self.assertIn("dblclick", arm3d)
        self.assertIn("splitLink6", arm3d)
        self.assertIn("setGripRange", arm3d)
        self.assertIn("gripT", arm3d)
        self.assertIn("jawLCad", arm3d)
        self.assertIn("stepGrip", arm3d)
        self.assertIn("GRIP_T_PER_S", arm3d)
        self.assertNotIn("0xf0c14b", arm3d)
        self.assertIn("0x8a9199", arm3d)
        self.assertIn("0xb8c0c8", arm3d)
        self.assertIn("0xc5cdd4", arm3d)
        self.assertNotIn("urdf_visual.json", arm3d)
        self.assertNotIn("0.752941176470588", arm3d)
        vis = json.loads((static / "meshes" / "urdf_visual.json").read_text(encoding="utf-8"))
        self.assertEqual(vis["source"], "fafu_baseV1.urdf")
        for name in ("base_link", "link1", "link2", "link3", "link4", "link5", "link6"):
            rgb = vis["links"][name]
            self.assertAlmostEqual(rgb[0], 0.752941176470588, places=5)
            self.assertAlmostEqual(rgb[1], 0.752941176470588, places=5)
            self.assertAlmostEqual(rgb[2], 0.752941176470588, places=5)
        js = (static / "js" / "app.js").read_text(encoding="utf-8")
        self.assertIn("telemFresh", js)
        self.assertIn("lastTelemAt", js)
        self.assertIn("paintGrip", js)
        self.assertIn("a.gripper_open", js)
        fafu_sim = (ROOT / "robot_station" / "adapters" / "fafu_sim.py").read_text(encoding="utf-8")
        self.assertIn("_GRIP_DEG_S", fafu_sim)
        self.assertIn("_step_gripper", fafu_sim)
        self.assertIn("_grip_tgt_deg", fafu_sim)
        mesh_dir = static / "meshes"
        for name in ("base_link", "link1", "link2", "link3", "link4", "link5", "link6"):
            blob = mesh_dir / (name + ".bin")
            self.assertTrue(blob.is_file(), blob)
            self.assertEqual(blob.read_bytes()[:4], b"FARM")
            self.assertGreater(blob.stat().st_size, 1000)
        self.assertIn("0.0584", arm3d)
        self.assertIn("-0.26", arm3d)
        self.assertIn("0.165", arm3d)
        self.assertIn("AxesHelper", arm3d)
        self.assertIn("baseAxes", arm3d)
        self.assertIn("eeAxes", arm3d)


if __name__ == "__main__":
    unittest.main()
